/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package guestbook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BookDetail service. Represents a row in the &quot;GB_BookDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>guestbook.model.impl.BookDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>guestbook.model.impl.BookDetailImpl</code>.
 * </p>
 *
 * @author linhpksw
 * @see BookDetail
 * @generated
 */
@ProviderType
public interface BookDetailModel
	extends BaseModel<BookDetail>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book detail model instance should use the {@link BookDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this book detail.
	 *
	 * @return the primary key of this book detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book detail.
	 *
	 * @param primaryKey the primary key of this book detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this book detail.
	 *
	 * @return the mvcc version of this book detail
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this book detail.
	 *
	 * @param mvccVersion the mvcc version of this book detail
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this book detail.
	 *
	 * @return the uuid of this book detail
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this book detail.
	 *
	 * @param uuid the uuid of this book detail
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the book ID of this book detail.
	 *
	 * @return the book ID of this book detail
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book detail.
	 *
	 * @param bookId the book ID of this book detail
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the title of this book detail.
	 *
	 * @return the title of this book detail
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this book detail.
	 *
	 * @param title the title of this book detail
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this book detail.
	 *
	 * @return the author of this book detail
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this book detail.
	 *
	 * @param author the author of this book detail
	 */
	public void setAuthor(String author);

	/**
	 * Returns the description of this book detail.
	 *
	 * @return the description of this book detail
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this book detail.
	 *
	 * @param description the description of this book detail
	 */
	public void setDescription(String description);

	/**
	 * Returns the isbn of this book detail.
	 *
	 * @return the isbn of this book detail
	 */
	@AutoEscape
	public String getIsbn();

	/**
	 * Sets the isbn of this book detail.
	 *
	 * @param isbn the isbn of this book detail
	 */
	public void setIsbn(String isbn);

	/**
	 * Returns the status of this book detail.
	 *
	 * @return the status of this book detail
	 */
	public int getStatus();

	/**
	 * Sets the status of this book detail.
	 *
	 * @param status the status of this book detail
	 */
	public void setStatus(int status);

	/**
	 * Returns the group ID of this book detail.
	 *
	 * @return the group ID of this book detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this book detail.
	 *
	 * @param groupId the group ID of this book detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this book detail.
	 *
	 * @return the company ID of this book detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this book detail.
	 *
	 * @param companyId the company ID of this book detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this book detail.
	 *
	 * @return the user ID of this book detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this book detail.
	 *
	 * @param userId the user ID of this book detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this book detail.
	 *
	 * @return the user uuid of this book detail
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this book detail.
	 *
	 * @param userUuid the user uuid of this book detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this book detail.
	 *
	 * @return the user name of this book detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this book detail.
	 *
	 * @param userName the user name of this book detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this book detail.
	 *
	 * @return the create date of this book detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this book detail.
	 *
	 * @param createDate the create date of this book detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this book detail.
	 *
	 * @return the modified date of this book detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this book detail.
	 *
	 * @param modifiedDate the modified date of this book detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public BookDetail cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}