/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package guestbook.model.impl;

import guestbook.model.BookDetail;

import guestbook.service.BookDetailLocalServiceUtil;

/**
 * The extended model base implementation for the BookDetail service. Represents a row in the &quot;GB_BookDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookDetailImpl}.
 * </p>
 *
 * @author linhpksw
 * @see BookDetailImpl
 * @see BookDetail
 * @generated
 */
public abstract class BookDetailBaseImpl
	extends BookDetailModelImpl implements BookDetail {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a book detail model instance should use the <code>BookDetail</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BookDetailLocalServiceUtil.addBookDetail(this);
		}
		else {
			BookDetailLocalServiceUtil.updateBookDetail(this);
		}
	}

}