/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package guestbook.model.impl;

import guestbook.model.BorrowEntry;

import guestbook.service.BorrowEntryLocalServiceUtil;

/**
 * The extended model base implementation for the BorrowEntry service. Represents a row in the &quot;GB_BorrowEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BorrowEntryImpl}.
 * </p>
 *
 * @author linhpksw
 * @see BorrowEntryImpl
 * @see BorrowEntry
 * @generated
 */
public abstract class BorrowEntryBaseImpl
	extends BorrowEntryModelImpl implements BorrowEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a borrow entry model instance should use the <code>BorrowEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BorrowEntryLocalServiceUtil.addBorrowEntry(this);
		}
		else {
			BorrowEntryLocalServiceUtil.updateBorrowEntry(this);
		}
	}

}